<?php
/**
 * TL_ROOT/system/modules/calendar_ical/languages/fr/default.php 
 * 
 * Contao extension: calendar_ical 1.3.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['ical']['0'] = "iCal";
$GLOBALS['TL_LANG']['MSC']['import_calendar']['0'] = "Importer un calendrier";
$GLOBALS['TL_LANG']['MSC']['export_calendar']['0'] = "Exporter un calendrier";
$GLOBALS['TL_LANG']['MSC']['location'] = "Emplacement";
 
?>
