<?php
/**
 * TL_ROOT/system/modules/calendar_ical/languages/fr/tl_calendar.php 
 * 
 * Contao extension: calendar_ical 1.3.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_calendar']['ical_alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_calendar']['ical_prefix']['0'] = "Préfixe du titre";
$GLOBALS['TL_LANG']['tl_calendar']['ical_description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_calendar']['ical_url']['0'] = "URL du fichier iCal";
 
?>
