<?php
/**
 * TL_ROOT/system/modules/calendar_ical/languages/de/default.php 
 * 
 * Contao extension: calendar_ical 1.4.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['ical']['0'] = "iCal";
$GLOBALS['TL_LANG']['CTE']['ical']['1'] = "Dieses Element erstellt einen Hyperlink auf eine vCalendar (iCal)-Datei, die heruntergeladen werden kann und dazu verwendet werden kann, die enthaltenen Termine in einer externen Kalenderanwendung anzuzeigen.";
$GLOBALS['TL_LANG']['MSC']['import_calendar']['0'] = "Kalender importieren";
$GLOBALS['TL_LANG']['MSC']['import_calendar']['1'] = "Importieren Sie eine iCal (.ics) Kalender-Datei in Ihren Kalender.";
$GLOBALS['TL_LANG']['MSC']['export_calendar']['0'] = "Kalender exportieren";
$GLOBALS['TL_LANG']['MSC']['export_calendar']['1'] = "Importieren Sie Ihren Kalender in eine iCal (.ics) Kalender-Datei.";
$GLOBALS['TL_LANG']['MSC']['location'] = "Ort";
$GLOBALS['TL_LANG']['ERR']['only_one_file'] = "Bitte wählen Sie nur eine Datei zum Hochladen aus!";
 
?>
