<?php
/**
 * TL_ROOT/system/modules/calendar_ical/languages/de/tl_calendar_events.php 
 * 
 * Contao extension: calendar_ical 1.4.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_calendar_events']['icssource']['0'] = "Datenquelle";
$GLOBALS['TL_LANG']['tl_calendar_events']['icssource']['1'] = "Bitte wählen Sie die iCal (.ics) Kalender-Datei oder die CSV-Datei (.csv) von Ihrem Gerät, die Sie importieren möchten.";
$GLOBALS['TL_LANG']['tl_calendar_events']['import']['0'] = "Kalender-Import";
$GLOBALS['TL_LANG']['tl_calendar_events']['import']['1'] = "Importieren Sie Termine aus einer iCal-Datei (.ics) oder einer CSV-Datei (.csv)";
$GLOBALS['TL_LANG']['tl_calendar_events']['check'] = "Überprüfen";
$GLOBALS['TL_LANG']['tl_calendar_events']['untitled'] = "Ohne Titel";
$GLOBALS['TL_LANG']['tl_calendar_events']['dateFormat'] = "%d.%m.%Y";
$GLOBALS['TL_LANG']['tl_calendar_events']['timeFormat'] = "%H:%M";
$GLOBALS['TL_LANG']['tl_calendar_events']['importStartDate']['0'] = "Startdatum";
$GLOBALS['TL_LANG']['tl_calendar_events']['importStartDate']['1'] = "Geben Sie das Startdatum für den Kalenderimport an. Alle Termine, die vor diesem Datum auftreten, werden nicht berücksichtigt.";
$GLOBALS['TL_LANG']['tl_calendar_events']['importEndDate']['0'] = "Enddatum";
$GLOBALS['TL_LANG']['tl_calendar_events']['importEndDate']['1'] = "Geben Sie das Enddatum für den Kalenderimport an. Alle Termine, die nach diesem Datum auftreten, werden nicht berücksichtigt.";
$GLOBALS['TL_LANG']['tl_calendar_events']['encoding']['0'] = "Zeichencodierung";
$GLOBALS['TL_LANG']['tl_calendar_events']['encoding']['1'] = "Bitte geben Sie die Zeichencodierung Ihrer zu importierenden Daten an.";
$GLOBALS['TL_LANG']['tl_calendar_events']['importDeleteCalendar']['0'] = "Bestehende Termine entfernen";
$GLOBALS['TL_LANG']['tl_calendar_events']['importDeleteCalendar']['1'] = "Wählen Sie diese Option, wenn Sie die bestehenden Termine in diesem Kalender vor dem Import der neuen Kalenderdaten entfernen wollen.";
$GLOBALS['TL_LANG']['tl_calendar_events']['correctTimezone']['0'] = "Zeitzone korrigieren";
$GLOBALS['TL_LANG']['tl_calendar_events']['correctTimezone']['1'] = "Wählen Sie diese Option, wenn Sie die Zeitzone der Importdatei ändern und durch die Zeitzone dieser TYPOlight-Installation ersetzen wollen.";
$GLOBALS['TL_LANG']['tl_calendar_events']['proceed']['0'] = "Weiter";
$GLOBALS['TL_LANG']['tl_calendar_events']['proceed']['1'] = "Weiter mit dem Importprozess";
$GLOBALS['TL_LANG']['tl_calendar_events']['timezone']['0'] = "Zeitzone";
$GLOBALS['TL_LANG']['tl_calendar_events']['timezone']['1'] = "Bitte wählen Sie die Zeitzone für die Import-Datei aus.";
$GLOBALS['TL_LANG']['tl_calendar_events']['confirmationTimezone'] = "TYPOlight hat festgestellt, dass sich die Systemzeitzone '%s' von der Zeitzone '%s' der Import-Datei unterscheidet. Dies kann zu Zeitverschiebungen bei den Terminen führen.";
$GLOBALS['TL_LANG']['tl_calendar_events']['confirmationMissingTZ'] = "TYPOlight hat festgestellt, dass die Import-Datei ohne Zeitzone erzeugt wurde. Ihre System-Zeitzone ist '%s'. Bitte wählen Sie eine Zeitzone für die Termine der Import-Datei aus. Beachten Sie, dass die Auswahl einer anderen Zeitzone als der ursprünglich für die Termine angedachten zu Zeitverschiebungen bei den Terminen führen kann.";
$GLOBALS['TL_LANG']['tl_calendar_events']['importDateFormat']['0'] = "Datumsformat";
$GLOBALS['TL_LANG']['tl_calendar_events']['importDateFormat']['1'] = "Bitte geben Sie das Datumsformat Ihrer zu importierenden Datumsfelder ein.";
$GLOBALS['TL_LANG']['tl_calendar_events']['importTimeFormat']['0'] = "Zeitformat";
$GLOBALS['TL_LANG']['tl_calendar_events']['importTimeFormat']['1'] = "Bitte geben Sie das Zeitformat Ihrer zu importierenden Zeitfelder ein.";
$GLOBALS['TL_LANG']['tl_calendar_events']['importTimeShift']['0'] = "Manuelle Zeitverschiebung";
$GLOBALS['TL_LANG']['tl_calendar_events']['importTimeShift']['1'] = "Bitte geben Sie die Anzahl der Stunden an, um die jeder Termin verschoben werden soll. Diese Option sollte nur genutzt werden, wenn die automatische Zeitzonen-Erkennung fehlschlägt.";
$GLOBALS['TL_LANG']['tl_calendar_events']['preview'] = "Daten-Vorschau";
$GLOBALS['TL_LANG']['tl_calendar_events']['fields'] = "Felder";
$GLOBALS['TL_LANG']['tl_calendar_events']['details']      = array('Event-Text', 'Hier können Sie den Event-Text eingeben.');
 
?>
