<?php
/**
 * TL_ROOT/system/modules/calendar_ical/languages/de/tl_calendar.php 
 * 
 * Contao extension: calendar_ical 1.4.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_calendar']['ical_alias']['0'] = "Kalender-Alias";
$GLOBALS['TL_LANG']['tl_calendar']['ical_alias']['1'] = "Hier können Sie einen eindeutigen Dateinamen (ohne Endung) eingeben. Die iCal-Abonnement-Datei wird automatisch im Wurzelverzeichnis Ihrer TYPOlight-Installation erstellt, z.B. als <em>name.ics</em>.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_prefix']['0'] = "Titel-Präfix";
$GLOBALS['TL_LANG']['tl_calendar']['ical_prefix']['1'] = "Bitte geben Sie ein Präfix ein, das in der iCal-Abonnement-Datei vor allen Event-Titeln ausgegeben wird.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_description']['0'] = "iCal Beschreibung";
$GLOBALS['TL_LANG']['tl_calendar']['ical_description']['1'] = "Bitte geben Sie eine kurze Beschreibung des iCal-Abonnements ein";
$GLOBALS['TL_LANG']['tl_calendar']['make_ical']['0'] = "iCal Abonnement erstellen";
$GLOBALS['TL_LANG']['tl_calendar']['make_ical']['1'] = "Eine iCal Abonnement Datei aus dem Kalender generieren";
$GLOBALS['TL_LANG']['tl_calendar']['ical_source']['0'] = "iCal Webdaten";
$GLOBALS['TL_LANG']['tl_calendar']['ical_source']['1'] = "Einen Kalender aus einer iCal Web-Datenquelle generieren";
$GLOBALS['TL_LANG']['tl_calendar']['ical_url']['0'] = "Kalender-URL";
$GLOBALS['TL_LANG']['tl_calendar']['ical_url']['1'] = "Bitte geben Sie die URL der .ics Quelldatei des iCal-Kalenders ein.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_cache']['0'] = "Cache-Dauer in Sekunden";
$GLOBALS['TL_LANG']['tl_calendar']['ical_cache']['1'] = "Bitte geben Sie die minimale Cache-Dauer in Sekunden für die Pufferung der iCal-Daten an. Die Kalenderdaten werden erst nach dem Ablauf der Cache-Dauer wieder neu aufgebaut.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_timezone']['0'] = "Zeitzone";
$GLOBALS['TL_LANG']['tl_calendar']['ical_timezone']['1'] = "Wählen Sie eine Zeitzone für den Kalender aus, falls im Kalender keine Zeitzone angegeben ist.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_start']['0'] = "Startdatum";
$GLOBALS['TL_LANG']['tl_calendar']['ical_start']['1'] = "Bitte geben Sie das Startdatum ein, ab dem TYPOlight Termine aus den ausgewählten Kalendern extrahieren soll. Wenn Sie kein Datum angeben, wird das aktuelle Datum als Startdatum verwendet.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_end']['0'] = "Enddatum";
$GLOBALS['TL_LANG']['tl_calendar']['ical_end']['1'] = "Bitte geben Sie das Endatum ein, bis zu dem TYPOlight Termine aus den ausgewählten Kalendern extrahieren soll.  Wenn Sie kein Datum angeben, wird das Datum in einem Jahr als Enddatum verwendet.";
$GLOBALS['TL_LANG']['tl_calendar']['ical_legend'] = "iCal Einstellungen";
 
?>
