<?php
/**
 * TL_ROOT/system/modules/calendar_ical/languages/de/tl_content.php 
 * 
 * Contao extension: calendar_ical 1.4.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['ical_calendar']['0'] = "Kalender";
$GLOBALS['TL_LANG']['tl_content']['ical_calendar']['1'] = "Bitte wählen Sie einen oder mehrere Kalender aus.";
$GLOBALS['TL_LANG']['tl_content']['ical_start']['0'] = "Startdatum";
$GLOBALS['TL_LANG']['tl_content']['ical_start']['1'] = "Bitte geben Sie das Startdatum ein, ab dem TYPOlight Termine aus den ausgewählten Kalendern extrahieren soll. Wenn Sie kein Datum angeben, wird das aktuelle Datum als Startdatum verwendet.";
$GLOBALS['TL_LANG']['tl_content']['ical_end']['0'] = "Enddatum";
$GLOBALS['TL_LANG']['tl_content']['ical_end']['1'] = "Bitte geben Sie das Endatum ein, bis zu dem TYPOlight Termine aus den ausgewählten Kalendern extrahieren soll.  Wenn Sie kein Datum angeben, wird das Datum in einem Jahr als Enddatum verwendet.";
$GLOBALS['TL_LANG']['tl_content']['ical_title'] = "iCal-Datei herunterladen";
$GLOBALS['TL_LANG']['tl_content']['ical_prefix']['0'] = "Titel-Präfix";
$GLOBALS['TL_LANG']['tl_content']['ical_prefix']['1'] = "Bitte geben Sie ein Präfix ein, das in der iCal-Abonnement-Datei vor allen Event-Titeln ausgegeben wird.";
$GLOBALS['TL_LANG']['tl_content']['calendar_legend'] = "Kalender-Einstellungen";
 
?>
